name: 'Scanner Registry Test Action'
description: 'Run scanner tests when changes are made to the scanner registry'
author: 'BoostSecurity'

branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  provider:
    description: 'CI/CD provider to use (github, gitlab, azure, bitbucket)'
    required: true
  provider-config:
    description: 'JSON configuration for the selected provider. See README for schema per provider.'
    required: true
  registry-path:
    description: 'Path to scanner registry repository'
    required: true
    default: '.'
  base-ref:
    description: 'Base git reference to compare against'
    required: true
    default: 'main'
  head-ref:
    description: 'Head git reference (current branch)'
    required: true

outputs:
  results:
    description: 'JSON-formatted test results'
    value: ${{ steps.run-tests.outputs.results }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        poetry install --only main

    - name: Run tests
      id: run-tests
      shell: bash
      env:
        PROVIDER_CONFIG: ${{ inputs.provider-config }}
      run: |
        cd ${{ github.action_path }}
        RESULTS=$(poetry run python -m boostsec.registry_test_action.cli \
          --registry-path "${{ inputs.registry-path }}" \
          --base-ref "${{ inputs.base-ref }}" \
          --head-ref "${{ inputs.head-ref }}" \
          --provider "${{ inputs.provider }}" \
          --provider-config "$PROVIDER_CONFIG")
        echo "results=$RESULTS" >> $GITHUB_OUTPUT
